
class BannedSongs {
  constructor() {
    this.bannedSongs = [
      "WAP",
      "My Neck, My Back (Lick It)",
      "Deepthroat",
      "Slob On My Knob",
      "F**kin' Problems",
      "I Love It",
      "Stupid Hoe",
      "Lollipop",
      "P***y Fairy (OTW)",
      "Work B**ch",
      "Or Nah",
      "Birthday Sex",
      "Freaky Friday",
      "P.I.M.P.",
      "Anaconda",
      "Boss A** B***h",
      "B***h Better Have My Money",
      "D**k",
      "No Hands",
      "Rich Sex",
      "Look Back At It",
      "Magic Stick",
      "Big Ole Freak",
      "How Many Licks?",
      "The Way You Love Me",
      "34+35",
      "Pornography",
      "Porn Star",
      "I Wanna F**k You",
      "Sex With Me",
      "S&M",
      "Love Me Harder",
      "Pony",
      "Ride",
      "Partition",
      "Rocket",
      "Neighbors Know My Name",
      "Motivation",
      "Sexual Healing",
      "Let's Get It On",
      "I Touch Myself",
      "Closer",
      "I Wanna Sex You Up",
      "I'm a Slave 4 U",
      "Do What U Want",
      "LoveGame",
      "Teeth",
      "Candy Shop",
      "Dark Horse",
      "Took Her to the O",
      "Crazy Story",
      "Back in Blood",
      "AHHH HA",
      "No Flockin'",
      "Armed & Dangerous",
      "Sum 2 Prove",
      "On Me",
      "Life is Good",
      "GOOBA",
      "Toosie Slide",
      "Everyday",
      "High Speed",
      "Hold Up Hold Up Hold Up",
      "6locc 6a6y",
      "PSA",
      "CAPO",
      "Camelot",
      "Is Ya Ready",
      "Make No Sense",
      "Neva Cared",
      "500lbs",
      "Dior",
      "Slut Me Out",
      "Trap Queen",
      "Cut Her Off",
      "Mask Off",
      "Star Shopping",
      "The Box",
      "Too Many Nights",
      "redrum",
      "like him",
      "ride wit me"
    ];
  }

  isSongBanned(songTitle) {
    const normalizedInput = songTitle.trim().toLowerCase();
    return this.bannedSongs.some(song => 
      normalizedInput === song.toLowerCase()
    );
  }
}

module.exports = BannedSongs;
